//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TestApp.rc
//
#define IDD_QGTESTAPP_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDI_QUANTUMGATE                 130
#define IDR_MENU                        131
#define IDD_IPFILTERS                   132
#define IDD_SECURITY_SETTINGS           134
#define IDD_ENDPOINT_DLG                136
#define IDD_AUTHENTICATION_DLG          138
#define IDD_IPSUBNET_LIMITS_DIALOG      140
#define IDD_UUID_DIALOG                 142
#define IDD_PEER_ACCESS_DIALOG          145
#define IDR_POPUPS                      147
#define IDD_QGTESTAPP_DIALOG_MAIN_TAB   148
#define IDD_QGTESTAPP_DIALOG_TESTEXTENDER_TAB 150
#define IDD_ALGORITHMS_DIALOG           152
#define IDD_SETTINGS                    154
#define IDD_IPREPUTATIONS_DIALOG        156
#define IDD_INFO_DIALOG                 158
#define IDD_PING_DIALOG                 160
#define IDD_QGTESTAPP_DIALOG_AVEXTENDER_TAB 162
#define IDD_SOCKS5EXTENDER_CONFIG       164
#define IDC_INIT                        1000
#define IDC_CONSOLE                     1001
#define IDC_DEINIT                      1002
#define IDC_IP                          1003
#define IDC_PORT                        1004
#define IDC_MASK                        1004
#define IDC_EXTENDER_GRACE_PERIOD       1004
#define IDC_CONNECT                     1005
#define IDC_IP2                         1005
#define IDC_TEST_IP                     1005
#define IDC_MSG_RND_MIN                 1005
#define IDC_SENDTEXT                    1006
#define IDC_IP_RANGE                    1006
#define IDC_MSG_RND_PREFIX_MIN          1006
#define IDC_SENDBUTTON                  1007
#define IDC_IP_RANGE2                   1007
#define IDC_MSG_RND_MAX                 1007
#define IDC_SERVERPORT                  1008
#define IDC_MSG_RND_PREFIX_MAX          1008
#define IDC_SENDCHECK                   1009
#define IDC_NUM_NOISE_MSG               1009
#define IDC_IPV6LB                      1009
#define IDC_SENDSECONDS                 1010
#define IDC_NOISE_MINSIZE               1010
#define IDC_ONLY_AUTHENTICATED_CHECK    1010
#define IDC_DISCONNECT                  1011
#define IDC_NOISE_MAXSIZE               1011
#define IDC_EXCLUDE_INBOUND_CHECK       1011
#define IDC_CONSOLE_CHECK               1012
#define IDC_SENDNOISE                   1012
#define IDC_CONNECT_RELAY               1012
#define IDC_EXCLUDE_OUTBOUND_CHECK      1012
#define IDC_SEND_DELAY                  1012
#define IDC_SENDSTRESS                  1013
#define IDC_HANDSHAKE_DELAY             1013
#define IDC_HAS_TEST_EXTENDER           1013
#define IDC_NUMSTRESSMESS               1014
#define IDC_HANDSHAKE_DURATION          1014
#define IDC_EXCLUDE_INBOUND_CHECK3      1014
#define IDC_HAS_STRESS_EXTENDER         1014
#define IDC_STRESSRESULT                1015
#define IDC_NUM_IPCON_ATTEMPTS          1015
#define IDC_LOCALPEERID                 1016
#define IDC_IPCON_ATTEMPTS_INTERVAL     1016
#define IDC_SEND_PRIORITY               1016
#define IDC_SENDPEERID                  1017
#define IDC_SENDFILE                    1017
#define IDC_IPREP_IMPROVE_INTERVAL      1017
#define IDC_CONSOLEWND_CHECK            1018
#define IDC_NOISE_MSG_INTERVAL          1018
#define IDC_LOCAL_UUID                  1018
#define IDC_AUTO_SENDFILE               1018
#define IDC_LOAD_STRESSEXTENDER         1019
#define IDC_COND_ACCEPT                 1019
#define IDC_HOPS                        1019
#define IDC_START_BENCHMARK             1019
#define IDC_USE_STRESSEXTENDER2         1020
#define IDC_USE_STRESSEXTENDER          1020
#define IDC_NUM_NOISE_MSG_MAX           1020
#define IDC_DISCONNECT_PEER             1020
#define IDC_RELAY_PEER                  1020
#define IDC_PING                        1020
#define IDC_RELAY_CONNECT_TIMEOUT       1021
#define IDC_PING_NUM_BYTES              1021
#define IDC_RELAY_GRACEPERIOD           1022
#define IDC_PING_RESULT                 1022
#define IDC_AUTOCONNECT_DISCONNECT      1023
#define IDC_RELAY_NUM_IPCON_ATTEMPTS    1023
#define IDC_PEERLIST                    1024
#define IDC_RELAY_IPCON_ATTEMPTS_INTERVAL 1024
#define IDC_PASSPHRASE                  1025
#define IDC_NOISE_AUTO_MAX_BANDWIDTH    1025
#define IDC_KEYUPDATE_MINSECS           1026
#define IDC_FILETRANSFER_LIST           1027
#define IDC_KEYUPDATE_MAXSECS           1027
#define IDC_TYPECOMBO                   1028
#define IDC_NOISE_AUTO_SATURATE         1028
#define IDC_ADDFILTER                   1029
#define IDC_KEYUPDATE_BYTES             1029
#define IDC_ADDFILTER2                  1030
#define IDC_REMOVEFILTER                1030
#define IDC_RESET_ALL                   1030
#define IDC_NOISE_AUTO_USE              1030
#define IDC_ADDFILTER3                  1031
#define IDC_TEST_BUTTON                 1031
#define IDC_CONNECT_TIMEOUT             1031
#define IDC_RESET_SELECTED              1031
#define IDC_IPFILTERS_LIST              1032
#define IDC_KEYUPDATE_MAXDURATION       1032
#define IDC_REFRESH                     1032
#define IDC_IP_TEST_RESULT              1033
#define IDC_MESSAGE_AGE_TOLERANCE       1034
#define IDC_USERNAME                    1035
#define IDC_NOISE_AUTO_MIN_BANDWIDTH    1035
#define IDC_PASSWORD                    1036
#define IDC_NOISE_AUTO_SECONDS          1036
#define IDC_IPSUBNETLIMIT_LIST          1037
#define IDC_TTL                         1037
#define IDC_TCP_PORT                    1037
#define IDC_REMOVELIMIT                 1038
#define IDC_TIMEOUT                     1038
#define IDC_MAX_CONNECTIONS             1039
#define IDC_ADDLIMIT                    1040
#define IDC_CIDR                        1041
#define IDC_PUB_PEM                     1041
#define IDC_PEER_UUID                   1042
#define IDC_BROWSE                      1042
#define IDC_GENERATE_PEER_UUID          1043
#define IDC_EXTENDER_UUID               1044
#define IDC_GENERATE_EXTENDER_UUID      1045
#define IDC_UUID                        1046
#define IDC_VALIDATE_UUID               1047
#define IDC_VALIDATION_RESULT           1048
#define IDC_SAVE_PRIV_KEY               1049
#define IDC_SAVE_PUB_KEY                1050
#define IDC_PEER_LIST                   1051
#define IDC_REMOVE_PEER                 1052
#define IDC_ACCESS_COMBO                1053
#define IDC_ADD_PEER                    1054
#define IDC_DEFAULT_ACCESS_COMBO        1055
#define IDC_ALG_COMBO                   1055
#define IDC_ALL_PEERS_LIST              1056
#define IDC_TAB_CTRL                    1057
#define IDC_CONSOLE2                    1058
#define IDC_HOPS_LABEL                  1059
#define IDC_RELAY_PEER_LABEL            1060
#define IDC_ONLY_RELAYED_CHECK          1061
#define IDC_CHECK1                      1062
#define IDC_SEND_AUDIO_CHECK            1062
#define IDC_CHECK2                      1063
#define IDC_IPV4LB                      1063
#define IDC_CHECK3                      1064
#define IDC_CREATE_UUID                 1064
#define IDC_CHECK4                      1065
#define IDC_FILE_PATH                   1065
#define IDC_CHECK5                      1066
#define IDC_IPREPUTATIONS_LIST          1066
#define IDC_BENCHMARK_SIZE              1066
#define IDC_CHECK6                      1067
#define IDC_REPUTATION                  1067
#define IDC_CHECK7                      1068
#define IDC_SET_REPUTATION              1068
#define IDC_CHECK8                      1069
#define IDC_EDIT1                       1069
#define IDC_INFO_TEXT                   1069
#define IDC_CHECK9                      1070
#define IDC_BUFFER_SIZE                 1070
#define IDC_CHECK10                     1071
#define IDC_INITIALIZE_AV               1071
#define IDC_CHECK11                     1072
#define IDC_VIDEO_PREVIEW               1072
#define IDC_CHECK12                     1073
#define IDC_VIDEO_DEVICES_COMBO         1073
#define IDC_CHECK13                     1074
#define IDC_AUDIO_DEVICES_COMBO         1074
#define IDC_CALL_BUTTON                 1075
#define IDC_CHECK15                     1076
#define IDC_HANGUP_BUTTON               1076
#define IDC_SEND_VIDEO_CHECK            1077
#define IDC_CHECK14                     1078
#define IDC_CALL_STATUS                 1078
#define IDC_CHECK16                     1079
#define IDC_CALL_DURATION               1079
#define IDC_CHECK17                     1080
#define IDC_INITIALIZE_AV2              1080
#define IDC_INITIALIZE_AUDIO            1080
#define IDC_PRIORITY_COMBO              1080
#define IDC_VIDEO_SIZE_COMBO            1080
#define IDC_CHECK18                     1081
#define IDC_PREVIEW_VIDEO               1081
#define IDC_CHECK19                     1082
#define IDC_PREVIEW_AUDIO               1082
#define IDC_REUSE_CONNECTION            1082
#define IDC_CHECK20                     1083
#define IDC_VIDEO_COMPRESSION_CHECK     1083
#define IDC_VERSION_INFO                1083
#define IDC_CHECK21                     1084
#define IDC_AUDIO_COMPRESSION_CHECK     1084
#define IDC_CHECK22                     1085
#define IDC_VIDEO_FILL_CHECK            1085
#define IDC_VIDEO_SIZE_FORCE            1086
#define ID_CONSOLE_ENABLED              32771
#define ID_CONSOLE_TERMINALWINDOW       32772
#define ID_LOCAL_SECURITYLEVEL          32773
#define ID_SECURITYLEVEL_ONE            32774
#define ID_SECURITYLEVEL_TWO            32775
#define ID_SECURITYLEVEL_THREE          32776
#define ID_SECURITYLEVEL_FOUR           32777
#define ID_SECURITYLEVEL_FIVE           32778
#define ID_LOCAL_INITIALIZE             32779
#define ID_LOCAL_DEINITIALIZE           32780
#define ID_EXTENDERS_STRESSEXTENDER     32781
#define ID_STRESSEXTENDER_LOAD          32782
#define ID_STRESSEXTENDER_USE           32783
#define ID_BENCHMARKS_CALLBACKS         32784
#define ID_BENCHMARKS_MUTEXES           32785
#define ID_CONSOLE_VERBOSITY            32786
#define ID_VERBOSITY_SILENT             32787
#define ID_VERBOSITY_MINIMAL            32788
#define ID_VERBOSITY_VERBOSE            32789
#define ID_VERBOSITY_DEBUG              32790
#define ID_VERBOSITY_NORMAL             32791
#define ID_BENCHMARKS_STRESSEXTENDER    32792
#define ID_STRESSEXTENDER_MESSAGES      32793
#define ID_TESTEXTENDER_LOAD            32794
#define ID_TESTEXTENDER_UNLOAD          32795
#define ID_ATTACKS_CONNECTWITHGARBAGE   32796
#define ID_LOCAL_IPFILTERS              32797
#define ID_LOCAL_LISTENERSENABLED       32798
#define ID_LOCAL_EXTENDERSENABLED       32799
#define ID_BENCHMARKS_THREADLOCALCACHE  32800
#define ID_STRESS_INITANDDEINITEXTENDERS 32801
#define ID_STRESS_CONNECTANDDISCONNECT  32802
#define ID_LOCAL_USECOMPRESSION         32803
#define ID_LOCAL_CUSTOMSECURITYSETTINGS 32804
#define ID_SECURITYLEVEL_CUSTOM         32805
#define ID_BENCHMARKS_COMPRESSION       32806
#define ID_EXTENDERS_SOCKS5EXTENDER     32807
#define ID_SOCKS5EXTENDER_LOAD          32808
#define ID_SOCKS5EXTENDER_CREDENTIALS   32809
#define ID_SOCKS5EXTENDER_AUTHENTICATION 32810
#define ID_SOCKS5EXTENDER_ACCEPTINCOMINGCONNECTIONS 32811
#define ID_EXTENDERS_LOADFROMMODULE     32812
#define ID_EXTENDERS_UNLOADFROMMODULE   32813
#define ID_SOCKS5EXTENDER_USECOMPRESSION 32814
#define ID_TESTEXTENDER_USECOMPRESSION  32815
#define ID_STRESSEXTENDER_USECOMPRESSION 32816
#define ID_LOCAL_IPSUBNETLIMITS         32817
#define ID_UTILS_UUIDGENERATIONANDVALIDATION 32818
#define ID_LOCAL_ALLOWUNAUTHENTICATEDPEERS 32819
#define ID_LOCAL_PEERACCESSSETTINGS     32820
#define ID_PEERACCESSSETTINGS_ADD       32821
#define ID_LOCAL_RELAYSENABLED          32822
#define ID_LOCAL_RELAYS_ENABLED         32823
#define ID_LOCAL_CONNECT                32824
#define ID_LOCAL_CONNECT32825           32825
#define ID_LOCAL_CONNECT_RELAYED        32826
#define ID_PEERLIST_DETAILS             32827
#define ID_PEERLIST_DISCONNECT          32828
#define ID_PEERLIST_VIEW_DETAILS        32829
#define ID_LOCAL_SUPPORTEDALGORITHMS    32830
#define ID_LOCAL_SETTINGS               32831
#define ID_SETTINGS_GENERAL             32832
#define ID_STRESSEXTENDER_EXCEPTIONTEST 32833
#define ID_EXCEPTIONTEST_STARTUP        32834
#define ID_EXCEPTIONTEST_POSTSTARTUP    32835
#define ID_EXCEPTIONTEST_PRESHUTDOWN    32836
#define ID_EXCEPTIONTEST_SHUTDOWN       32837
#define ID_EXCEPTIONTEST_PEEREVENT      32838
#define ID_EXCEPTIONTEST_PEERMESSAGE    32839
#define ID_BENCHMARKS_CONSOLE           32840
#define ID_STRESS_MULTIPLEINSTANCES     32841
#define ID_BENCHMARKS_MEMORY            32842
#define ID_UTILS_LOGPOOLALLOCATORSTATISTICS 32843
#define ID_LOCAL_IPREPUTATIONS          32844
#define ID_ATTACKS_CONNECTANDDISCONNECT 32845
#define ID_ATTACKS_CONNECTANDWAIT       32846
#define ID_LOCAL_ENVIRONMENTINFO        32847
#define ID_UTILS_PING                   32848
#define ID_EXTENDERS_AVEXTENDER         32849
#define ID_AVEXTENDER_LOAD              32850
#define ID_AVEXTENDER_USECOMPRESSION    32851
#define ID_PEERLIST_CREATE_RELAY        32852
#define ID_LOCAL_FREEUNUSEDMEMORY       32853
#define ID_BENCHMARKS_THREADPAUSE       32854
#define ID_SOCKS5EXTENDER_CONFIGURATION 32855

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        166
#define _APS_NEXT_COMMAND_VALUE         32856
#define _APS_NEXT_CONTROL_VALUE         1084
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
